# Ansible Workfow for VMWare Management.
# docker-compose build && docker-compose run cli playbooks/vsphere/pb.get-vcenter-info.yml
# docker run  --network="host" --env-file .env h4ndzdatm0ld/vmware-mgmt:latest playbooks/vsphere/pb.get-vcenter-info.yml
---
- name: "VCENTER INFORMATION & TESTS"
  hosts: "localhost"
  gather_facts: false
  collections:
    - "vmware.vmware_rest"

  tasks:
    - name: "COLLECT DATACENTER INFORMATION"
      vmware.vmware_rest.vcenter_datacenter_info:
      register: "DATACENTERS"
    - debug:
        msg: "{{ DATACENTERS }}"

    - name: "COLLECT VMs"
      vmware.vmware_rest.vcenter_vm_info:
      register: EXISTING_VMS
      until: "EXISTING_VMS is not failed"
    - debug:
        msg: "{{ EXISTING_VMS }}"
