# Ansible Workfow for VMWare Management.
# docker-compose build && docker-compose run cli playbooks/vsphere/pb.get-vcenter-info.yml
---
- name: "VCENTER INFORMATION & TESTS"
  hosts: "localhost"
  gather_facts: false
  collections:
    - "vmware.vmware_rest"

  tasks:
    - name: "SET CONNECTION FACTS"
      ansible.builtin.set_fact:
        connection_args:
          vcenter_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
          vcenter_username: "{{ lookup('env', 'VMWARE_USER') }}"
          vcenter_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
          vcenter_validate_certs: "{{ lookup('env', 'VMWARE_VALIDATE_CERTS') }}"

    - name: "COLLECT DATACENTER INFORMATION"
      vmware.vmware_rest.vcenter_datacenter_info:
      register: "DATACENTERS"
    - debug:
        msg: "{{ DATACENTERS }}"

    - name: "COLLECT VMs"
      vmware.vmware_rest.vcenter_vm_info:
      register: EXISTING_VMS
      until: "EXISTING_VMS is not failed"
    - debug:
        msg: "{{ EXISTING_VMS }}"

    - name: "COLLECT INFO ABOUT 1 VM"
      vmware.vmware_rest.vcenter_vm_info:
        vm: '{{ EXISTING_VMS.value[0].vm }}'
      register: "test_vm1_info"
    - debug:
        msg: "{{ test_vm1_info }}"
