---
- name: "VCENTER INFORMATION & TESTS"
  hosts: "CrunchyCluster"
  gather_facts: true
  tasks:
    - name: "DEBUG"
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"
      tags:
        - "debug"

    - name: "UPDATE ALL PACKAGES"
      ansible.builtin.apt:
        name: "*"
        state: "latest"
      become: true
      when: "ansible_facts['distribution'] == 'Ubuntu'"

    - name: "INSTALL SPECIFIC PACKAGES DEFINED"
      ansible.builtin.apt:
        pkg:
          - "network-manager"
        state: "latest"
      become: true
