---
version: "3.8"
services:
  test:
    build:
      target: test
      context: .

  cli:
    build:
      target: cli
      context: .
    network_mode: host # Allow local host access.
    environment:
      ANSIBLE_COLLECTIONS_PATH: /usr/share/ansible/collections
      ANSIBLE_ROLES_PATH: /usr/share/ansible/roles
      WORKSTATION_URL: ${WORKSTATION_URL}
      WORKSTRATION_USERNAME: ${WORKSTRATION_USERNAME}
      WORKSTRATION_PASSWORD: ${WORKSTRATION_PASSWORD}
      WORKSTRATION_PORT: ${WORKSTRATION_PORT}
      CLONED_VM_NAME: ${CLONED_VM_NAME}
      WORKSTATION_PROJECTS_DIR: ${WORKSTATION_PROJECTS_DIR}
      VM_ID: ${VM_ID}
    image: ${COMMIT_IMAGE:-h4ndzdatm0ld/vmware-mgmt:cli}
