---
version: "3.8"
services:
  test:
    build:
      target: test
      context: .
  cli:
    build:
      target: cli
      context: .
    network_mode: host
    environment:
      ANSIBLE_COLLECTIONS_PATH: /usr/share/ansible/collections
      ANSIBLE_ROLES_PATH: /usr/share/ansible/roles
      ANSIBLE_USER: ${ANSIBLE_USER}
      ANSIBLE_SSH_PASSWORD: ${ANSIBLE_SSH_PASSWORD}
      VMWARE_HOST: ${VMWARE_HOST}
      VMWARE_USER: ${VMWARE_USER}
      VMWARE_PASSWORD: ${VMWARE_PASSWORD}
      VMWARE_VALIDATE_CERTS: ${VMWARE_VALIDATE_CERTS}
      PRE_SHARED_SECRET: ${PRE_SHARED_SECRET}
      VPN_PASSWORD: ${VPN_PASSWORD}
      VPN_USER: ${VPN_USER}
      COMMUNITY: ${COMMUNITY}
    volumes:
      - "./:/usr/src/app"
    image: ${COMMIT_IMAGE:-h4ndzdatm0ld/vmware-mgmt:latest}
