---
version: "3.8"
services:
  test:
    build:
      target: test
      context: .
  cli:
    build:
      target: cli
      context: .
    network_mode: host # Allow local host access.
    environment:
      ANSIBLE_COLLECTIONS_PATH: /usr/share/ansible/collections
      ANSIBLE_ROLES_PATH: /usr/share/ansible/roles
      WORKSTATION_URL: ${WORKSTATION_URL}
      WORKSTRATION_USERNAME: ${WORKSTRATION_USERNAME}
      WORKSTRATION_PASSWORD: ${WORKSTRATION_PASSWORD}
      WORKSTRATION_PORT: ${WORKSTRATION_PORT}
      CLONED_VM_NAME: ${CLONED_VM_NAME}
      WORKSTATION_PROJECTS_DIR: ${WORKSTATION_PROJECTS_DIR}
      VM_ID: ${VM_ID}
      ANSIBLE_USER: ${ANSIBLE_USER}
      ANSIBLE_SSH_PASSWORD: ${ANSIBLE_SSH_PASSWORD}
      VMWARE_HOST: ${VMWARE_HOST}
      VMWARE_USER: ${VMWARE_USER}
      VMWARE_PASSWORD: ${VMWARE_PASSWORD}
      VMWARE_VALIDATE_CERTS: ${VMWARE_VALIDATE_CERTS}
      PRE_SHARED_SECRET: ${PRE_SHARED_SECRET}
      VPN_PASSWORD: ${VPN_PASSWORD}
      VPN_USER: ${VPN_USER}
      COMMUNITY: ${COMMUNITY}
    volumes:
      - "./:/usr/src/app"
    image: ${COMMIT_IMAGE:-h4ndzdatm0ld/vmware-mgmt:latest}
  packer:
    build:
      target: packer
      context: .
    working_dir: "/usr/src/app"
    network_mode: "host" # Allow local host access.
    environment:
      PACKER_PLUGIN_PATH: /usr/src/app/packer-build/.packer.d/plugins
      VMWARE_HOST: ${VMWARE_HOST}
      VMWARE_USER: ${VMWARE_USER}
      VMWARE_PASSWORD: ${VMWARE_PASSWORD}
      VMWARE_VALIDATE_CERTS: ${VMWARE_VALIDATE_CERTS}
    volumes:
      - ".:/usr/src/app"
  terraform:
    env_file:
      - ".env"
    image: "hashicorp/terraform:latest"
    working_dir: "/usr/src/app"
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      TF_VAR_DO_TOKEN: "${TF_DO_TOKEN}"
      DO_TOKEN: "${DO_TOKEN}"
      TF_VAR_AWS_ACCESS_KEY_ID: "${TF_VAR_AWS_ACCESS_KEY_ID}"
      TF_VAR_AWS_SECRET_ACCESS_KEY: "${TF_VAR_AWS_SECRET_ACCESS_KEY}"
    volumes:
      - "./:/usr/src/app"