---
all:
  children:
    network_devices:
      hosts:
        EdgeRouterX:
          ansible_host: "192.168.0.1"
          ansible_network_os: "edgeos"
    servers:
      children:
        servers_workstation:
          hosts:
            ipfabric-dev:
              ansible_host: "192.168.4.137"
            rundeck:
              ansible_host: "192.168.4.41"
        servers_esxi:
          hosts:
            nautobot-aws:
              ansible_host: "192.168.100.140"
            nautobot-nvidia:
              ansible_host: "192.168.100.141"
            nautobot-training:
              ansible_host: "192.168.100.142"
            netbox:
              ansible_host: "192.168.100.143"
            nautobot-dev:
              ansible_host: "192.168.100.220"
            rundeck-dev:
              ansible_host: "192.168.100.186"
            job-runner-01:
              ansible_host: "192.168.100.187"
        network:
          hosts:
            uisp:
              ansible_host: "192.168.100.249"
            nautobot:
              ansible_host: "192.168.100.238"
