---
all:
  children:
    network_devices:
      hosts:
        EdgeRouterX:
          ansible_host: "192.168.0.1"
          ansible_network_os: "edgeos"
    network:
      hosts:
        uisp:
          ansible_host: "192.168.100.249"
        nautobot:
          ansible_host: "192.168.100.238"
