---
all:
  hosts:
    devpop:
      ansible_host: "127.0.0.1"
    EdgeRouterX:
      ansible_host: "192.168.0.1"
      ansible_network_os: "edgeos"
  children:
    nautobot_servers:
      hosts:
        nautobot_nvidia:
          ansible_host: "192.168.4.38"
        nautobot_aws:
          ansible_host: "192.168.4.39"
        nautobot_ipfabric:
          ansible_host: "192.168.4.40"
