---
all:
  hosts:
    devpop:
      ansible_host: "127.0.0.1"
    EdgeRouterX:
      ansible_host: "192.168.0.1"
      ansible_network_os: "edgeos"
  children:
    servers:
      children:
        servers_workstation:
          hosts:
            nautobot_ipfabric:
              ansible_host: "192.168.4.44"
        servers_esxi:
          hosts:
            nautobot-aws:
              ansible_host: "192.168.100.140"
            nautobot-nvidia:
              ansible_host: "192.168.100.141"
    aux_esxi_servers:
      hosts:
        rundeck:
          ansible_host: "192.168.4.41"
