# docker-compose run cli playbooks/common/pb.onboard.yml -i inventory/vsphere.yml
---
- hosts: "all"
  gather_facts: true
  become: true
  become_user: "root"
  tasks:
    - name: "UPDATE NAMESERVER ENTRY"
      ansible.builtin.lineinfile:
        path: "/etc/resolv.conf"
        line: "nameserver {{ item }}"
      loop: "{{ nameservers }}"

    - name: "UPDATE CACHE"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
      register: "APTGET"
    - debug:
        var: "APTGET"

    - name: "UPDATE ALL PACKAGES TO LATEST"
      apt:
        name: "*"
        state: latest
      register: "UPDATE"
      become: true
    - debug:
        var: "UPDATE"

    - name: "INSTALL SPECIFIC PACKAGES DEFINED"
      apt:
        pkg:
          - "netplan.io"
          - "needrestart"
          - "resolvconf"
          - "open-vm-tools-desktop"
          - "fuse"
          - "net-tools"
          - "network-manager"
          - "nfs-common"
          - "nfs-kernel-server"
          - "rsync"
        state: "latest"

    - name: "Add FQDN to /etc/hosts"
      lineinfile:
        dest: "/etc/hosts"
        regexp: '^127\.0\.1\.1' # yamllint disable
        line: "127.0.1.1 {{ inventory_hostname  | replace('_', '-') }} {{ inventory_hostname_short }}"
        state: "present"
