---
ansible_ssh_password: "{{ lookup('env', 'ANSIBLE_SSH_PASSWORD') }}"
ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
ansible_become_password: "{{ lookup('env', 'ANSIBLE_SSH_PASSWORD') }}"
vcenter_hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
vcenter_username: "{{ lookup('env', 'VMWARE_USER') }}"
vcenter_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
vcenter_validate_certs: "{{ lookup('env', 'VMWARE_VALIDATE_CERTS') }}"
shared_media: false
nameservers:
  - "192.168.4.1"
  - "192.168.0.1"
  - "192.168.100.1"
  - "8.8.8.8"
  - "1.1.1.1"
mgmt_subnet_mask: "255.255.255.0"
mgmt_subnet_prefix: "24"

networks:
  crunchy_mgmt: "192.168.100.0/24"
  data_closet: "192.168.2.0/23"
  office_desk: "192.168.4.0/24"
ANSIBLE_PERSISTENT_COMMAND_TIMEOUT: 30
