---
name: "CI-Docker-Build"

on:
  push:
    branches: ["*"]

jobs:
  build:
    name: "Login to Docker Hub"
    runs-on: "ubuntu-latest"
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Docker Compose Build"
        run: "docker-compose build"

      - name: "Docker Push"
        run: "docker push ${{ secrets.DOCKERHUB_USERNAME }}/vmware-mgmt:cli"
