---
name: "CI-Docker-Build"

on: # yamllint disable
  push:
    branches: ["main"]

jobs:
  build:
    name: "Publish to Docker Registry"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Docker Compose Build"
        run: "docker-compose build"

      - name: "Docker Push"
        run: "docker push ${{ secrets.DOCKERHUB_USERNAME }}/vmware-mgmt"
